### ISSUE TITLE
RealSense launch trouble

### ISSUE THREAD

**Issue by yucolabjames** [OpenPTrack/open_ptrack_v2#90]
Am trying the realsense implementation, fully aware it's still under development. It seems am having some trouble to get it working, here are the steps I followed:

1. Installed the librealsense from [Intel's Github](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md):
```
sudo apt-key adv --keyserver keys.gnupg.net --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
sudo add-apt-repository "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic main" -u
sudo apt-get install librealsense2-dkms
sudo apt-get install librealsense2-utils
```
2. From the `realsense-viewer` I upgraded the D435 firmware 5.11.15.0
3. Pulled openptrack's dev branch: [(As explained here)](https://github.com/OpenPTrack/open_ptrack_v2/issues/51#issuecomment-464402472)
```
git clone -b dev https://github.com/OpenPTrack/open_ptrack_docker_config.git
cd open_ptrack_docker_config/single_camera_tracking/
./run_single_camera
```
4. From the container
```
roslaunch tracking single_camera_tracking_node.launch enable_pose:=false enable_people_tracking:=true enable_object:=false sensor_type:=realsense
```
5. Run into the error `ResourceNotFound: realsense2_camera` 

Here is the console log for your reference:
```
engine@yucolab-engine:~/dev/open_ptrack_docker_config/single_camera_tracking$ ./run_single_camera 
open_ptrack_single_camera container exist.
Starting open_ptrack_single_camera container. 
access control disabled, clients can connect from any host
open_ptrack_single_camera
root@yucolab-engine:~# roslaunch tracking single_camera_tracking_node.launch enable_pose:=false enable_people_tracking:=true enable_object:=true sensor_type:=realsense
... logging to /root/.ros/log/92ac7a6e-e10b-11e9-bee6-9c5c8ebb7ad7/roslaunch-yucolab-engine-121.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 749, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 721, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 685, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 627, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 685, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 589, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: realsense2_camera
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/root/workspace/ros/src
ROS path [2]=/opt/ros/kinetic/share
root@yucolab-engine:~# 
```

My hardware detail:
Ubuntu 18.04.3 LTS x64
Memory 15.6 GiB
Intel® Core™ i7-7700 CPU @ 3.60GHz × 8
GeForce GT 1030/PCIe/SSE2
Intel RealSense D435

Log file from the docker:
[roslaunch-yucolab-engine-121.log](https://github.com/OpenPTrack/open_ptrack_v2/files/3662195/roslaunch-yucolab-engine-121.log)

**Comment by bsubbaraman** [comment]
Hi @yucolabjames.

With the most recent commit to the [open_ptrack_docker_config repo](https://github.com/OpenPTrack/open_ptrack_docker_config/tree/dev), we are using an updated docker image from which you should be able to launch a realsense without installing any external dependencies.

Please stop and remove any existing single camera docker containers by running `./run_single_camera -sr`.  (If you list all active docker containers with `docker ps -a`, there shouldn't by any containers with 'single_camera' in the name after this).  Then try re-starting the single camera container and launching the RealSense.  This should work for you!

Let me know if the above steps work to launch the RealSense for you.

**Comment by yucolabjames** [comment]
Nice I got it working @bsubbaraman thanks for pointing me into the right direction. Just for reference, here is what I did.

Vim edit `./run_single_camera` to amend the image name
```
image_name=openptrackofficial/1604:latest
```

Remove all stopped and unused docker images (WARNING: could be a bad idea if you have other images you need)
```
sudo docker system prune -a
```

Double check if openptrack is still here
```
docker images -a
```
Then proceed to grabbing the correct image again by running
```
./run_single_camera
```

And done!
```
roslaunch tracking single_camera_tracking_node.launch enable_pose:=false enable_people_tracking:=true enable_object:=false sensor_type:=realsense
```

Cheers, thanks for the help again!
